-- CreateTable
CREATE TABLE `department` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `departmentCode` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `uname` VARCHAR(191) NOT NULL DEFAULT 'Staffid',

    UNIQUE INDEX `department_departmentCode_key`(`departmentCode`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `code` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `depCode` VARCHAR(191) NOT NULL,
    `uname` VARCHAR(191) NOT NULL DEFAULT 'Staffid',

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `student` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `regNo` VARCHAR(191) NOT NULL,
    `claass` VARCHAR(191) NOT NULL,
    `section` VARCHAR(191) NOT NULL,
    `codeId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `marks` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `C1Q1` DOUBLE NULL,
    `C1Q2` DOUBLE NULL,
    `C1Q3` DOUBLE NULL,
    `C1Q4` DOUBLE NULL,
    `C1Q5` DOUBLE NULL,
    `C1Q6` DOUBLE NULL,
    `C1Q7` DOUBLE NULL,
    `C1Q8` DOUBLE NULL,
    `C1Q9` DOUBLE NULL,
    `C1Q10` DOUBLE NULL,
    `C1Q11` DOUBLE NULL,
    `C1Q12` DOUBLE NULL,
    `C1Q13` DOUBLE NULL,
    `C1Q14` DOUBLE NULL,
    `C1Q15` DOUBLE NULL,
    `C1Q16` DOUBLE NULL,
    `C1Q17` DOUBLE NULL,
    `C1Q18` DOUBLE NULL,
    `C1Q19` DOUBLE NULL,
    `C1Q20` DOUBLE NULL,
    `C1Q21` DOUBLE NULL,
    `C1Q22` DOUBLE NULL,
    `C1Q23` DOUBLE NULL,
    `C1Q24` DOUBLE NULL,
    `C1Q25` DOUBLE NULL,
    `C1Q26` DOUBLE NULL,
    `C1Q27` DOUBLE NULL,
    `C1Q28` DOUBLE NULL,
    `C2Q1` DOUBLE NULL,
    `C2Q2` DOUBLE NULL,
    `C2Q3` DOUBLE NULL,
    `C2Q4` DOUBLE NULL,
    `C2Q5` DOUBLE NULL,
    `C2Q6` DOUBLE NULL,
    `C2Q7` DOUBLE NULL,
    `C2Q8` DOUBLE NULL,
    `C2Q9` DOUBLE NULL,
    `C2Q10` DOUBLE NULL,
    `C2Q11` DOUBLE NULL,
    `C2Q12` DOUBLE NULL,
    `C2Q13` DOUBLE NULL,
    `C2Q14` DOUBLE NULL,
    `C2Q15` DOUBLE NULL,
    `C2Q16` DOUBLE NULL,
    `C2Q17` DOUBLE NULL,
    `C2Q18` DOUBLE NULL,
    `C2Q19` DOUBLE NULL,
    `C2Q20` DOUBLE NULL,
    `C2Q21` DOUBLE NULL,
    `C2Q22` DOUBLE NULL,
    `C2Q23` DOUBLE NULL,
    `C2Q24` DOUBLE NULL,
    `C2Q25` DOUBLE NULL,
    `C2Q26` DOUBLE NULL,
    `C2Q27` DOUBLE NULL,
    `C2Q28` DOUBLE NULL,
    `ESEQ1` DOUBLE NULL,
    `ESEQ2` DOUBLE NULL,
    `ESEQ3` DOUBLE NULL,
    `ESEQ4` DOUBLE NULL,
    `ESEQ5` DOUBLE NULL,
    `ESEQ6` DOUBLE NULL,
    `ESEQ7` DOUBLE NULL,
    `ESEQ8` DOUBLE NULL,
    `ESEQ9` DOUBLE NULL,
    `ESEQ10` DOUBLE NULL,
    `ESEQ11` DOUBLE NULL,
    `ESEQ12` DOUBLE NULL,
    `ESEQ13` DOUBLE NULL,
    `ESEQ14` DOUBLE NULL,
    `ESEQ15` DOUBLE NULL,
    `ESEQ16` DOUBLE NULL,
    `ESEQ17` DOUBLE NULL,
    `ESEQ18` DOUBLE NULL,
    `ESEQ19` DOUBLE NULL,
    `ESEQ20` DOUBLE NULL,
    `ESEQ21` DOUBLE NULL,
    `ESEQ22` DOUBLE NULL,
    `ESEQ23` DOUBLE NULL,
    `ESEQ24` DOUBLE NULL,
    `ESEQ25` DOUBLE NULL,
    `ESEQ26` DOUBLE NULL,
    `ESEQ27` DOUBLE NULL,
    `ESEQ28` DOUBLE NULL,
    `ASG1` DOUBLE NULL,
    `ASG2` DOUBLE NULL,
    `ASGCO1` DOUBLE NULL,
    `ASGCO2` DOUBLE NULL,
    `C1CO1` DOUBLE NULL,
    `C1CO2` DOUBLE NULL,
    `C1CO3` DOUBLE NULL,
    `C1CO4` DOUBLE NULL,
    `C1CO5` DOUBLE NULL,
    `C2CO1` DOUBLE NULL,
    `C2CO2` DOUBLE NULL,
    `C2CO3` DOUBLE NULL,
    `C2CO4` DOUBLE NULL,
    `C2CO5` DOUBLE NULL,
    `ESECO1` DOUBLE NULL,
    `ESECO2` DOUBLE NULL,
    `ESECO3` DOUBLE NULL,
    `ESECO4` DOUBLE NULL,
    `ESECO5` DOUBLE NULL,
    `TCO1` DOUBLE NULL,
    `TCO2` DOUBLE NULL,
    `TCO3` DOUBLE NULL,
    `TCO4` DOUBLE NULL,
    `TCO5` DOUBLE NULL,
    `C1STATUS` VARCHAR(191) NULL,
    `C2STATUS` VARCHAR(191) NULL,
    `ESESTATUS` VARCHAR(191) NULL,
    `C1STAFF` VARCHAR(191) NULL,
    `C2STAFF` VARCHAR(191) NULL,
    `ESESTAFF` VARCHAR(191) NULL,
    `ASG1STAFF` VARCHAR(191) NULL,
    `ASG2STAFF` VARCHAR(191) NULL,
    `studentId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PSO` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `PSO1CO1` INTEGER NOT NULL,
    `PSO1CO2` INTEGER NOT NULL,
    `PSO1CO3` INTEGER NOT NULL,
    `PSO1CO4` INTEGER NOT NULL,
    `PSO1CO5` INTEGER NOT NULL,
    `PSO2CO1` INTEGER NOT NULL,
    `PSO2CO2` INTEGER NOT NULL,
    `PSO2CO3` INTEGER NOT NULL,
    `PSO2CO4` INTEGER NOT NULL,
    `PSO2CO5` INTEGER NOT NULL,
    `PSO3CO1` INTEGER NOT NULL,
    `PSO3CO2` INTEGER NOT NULL,
    `PSO3CO3` INTEGER NOT NULL,
    `PSO3CO4` INTEGER NOT NULL,
    `PSO3CO5` INTEGER NOT NULL,
    `PSO4CO1` INTEGER NOT NULL,
    `PSO4CO2` INTEGER NOT NULL,
    `PSO4CO3` INTEGER NOT NULL,
    `PSO4CO4` INTEGER NOT NULL,
    `PSO4CO5` INTEGER NOT NULL,
    `PSO5CO1` INTEGER NOT NULL,
    `PSO5CO2` INTEGER NOT NULL,
    `PSO5CO3` INTEGER NOT NULL,
    `PSO5CO4` INTEGER NOT NULL,
    `PSO5CO5` INTEGER NOT NULL,
    `codeId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `role` ENUM('Admin', 'Staff') NOT NULL DEFAULT 'Staff',
    `name` VARCHAR(191) NOT NULL DEFAULT 'none',

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `code` ADD CONSTRAINT `code_depCode_fkey` FOREIGN KEY (`depCode`) REFERENCES `department`(`departmentCode`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `student` ADD CONSTRAINT `student_codeId_fkey` FOREIGN KEY (`codeId`) REFERENCES `code`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `marks` ADD CONSTRAINT `marks_studentId_fkey` FOREIGN KEY (`studentId`) REFERENCES `student`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PSO` ADD CONSTRAINT `PSO_codeId_fkey` FOREIGN KEY (`codeId`) REFERENCES `code`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
